# fly.toml app configuration file generated for mini-python-code-editor on 2025-05-29T10:54:12+05:30
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'mini-python-code-editor'
primary_region = 'bom'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
